//Package model :
//Describing the object structure
package model

//Object :
// Object only contains a name and is associated to a ID generated by sqlite
type Object struct {
	ID   uint64
	Name string
}

//NewObject :
// Constructor
func NewObject(name string) *Object {
	res := new(Object)
	res.Name = name

	return res
}
