//Package model :
//Describing the subject structure
package model

//Subject :
// Subject only contains a name and is associated to a ID generated by sqlite
type Subject struct {
	ID   uint64
	Name string
}

//NewSubject :
// Constructor
func NewSubject(name string) *Subject {
	res := new(Subject)
	res.Name = name

	return res
}
