//Package model :
//Describing the domain structure
package model

import (
	"errors"
	"iam/core/constant"
)

//Domain :
// Domain only contains a name and is associated to a ID generated by sqlite
type Domain struct {
	ID   uint64 `gorm:"unique;not null"`
	Name string
}

//NewDomain :
// Constructor
func NewDomain(name string) (*Domain, error) {
	switch {
	case len(name) > constant.NAME_MAX_LEN:
		return nil, errors.New("the name cannot be longer that 255 characters")
	case len(name) == 0:
		return nil, errors.New("the name cannot be empty")
	}

	res := new(Domain)
	res.Name = name

	return res, nil
}

//GetRootDomain :
// Should not be called in normal workflow
// Used only in database initialization
func GetRootDomain() *Domain {
	res := new(Domain)
	res.Name = ""

	return res
}
