//Package model :
//Describing the domain structure
package model

import (
	"errors"

	"iam/core"
)

//Domain :
// Domain only contains a name and is associated to a ID generated by sqlite
type Domain struct {
	ID   uint64 `gorm:"unique;not null"`
	Name string
}

//NewDomain :
// Constructor
func NewDomain(name string) (*Domain, error) {
	if len(name) > core.NAME_MAX_LEN {
		return nil, errors.New("the name cannot be longer that 255 characters")
	}

	res := new(Domain)
	res.Name = name

	return res, nil
}

//TODO : find a way to create safely the empty domain common of everyone
