//Package model :
//Describing the object structure
package model

import (
	"errors"

	"iam/core"
)

//Object :
// Object only contains a name and is associated to a ID generated by sqlite
type Object struct {
	ID   uint64 `gorm:"unique;not null"`
	Name string
}

//NewObject :
// Constructor
func NewObject(name string) (*Object, error) {
	if len(name) > core.NAME_MAX_LEN {
		return nil, errors.New("the name cannot be longer that 255 characters")
	}

	res := new(Object)
	res.Name = name

	return res, nil
}
