//Package model :
//Describing the subject structure
package model

import (
	"errors"

	"iam/core"
)

//Subject :
// Subject only contains a name and is associated to a ID generated by sqlite
type Subject struct {
	ID   uint64 `gorm:"unique;not null"`
	Name string
}

//NewSubject :
// Constructor
func NewSubject(name string) (*Subject, error) {
	if len(name) > core.NAME_MAX_LEN {
		return nil, errors.New("the name cannot be longer that 255 characters")
	}

	res := new(Subject)
	res.Name = name

	return res, nil
}
