//Package model :
//Describing the subject structure
package model

import (
	"errors"
	"iam/core/constant"
)

//Subject :
// Subject only contains a name and is associated to a ID generated by sqlite
type Subject struct {
	ID   uint64 `gorm:"unique;not null"`
	Name string
}

//NewSubject :
// Constructor
func NewSubject(name string) (*Subject, error) {
	switch {
	case len(name) > constant.NAME_MAX_LEN:
		return nil, errors.New("the name cannot be longer that 255 characters")
	case len(name) == 0:
		return nil, errors.New("the name cannot be empty")
	}

	res := new(Subject)
	res.Name = name

	return res, nil
}
